[LT-534-ADR]
arbisoft/edx-ora2-1 pull request #59
Opened 2022-04-06 22:53 UTC by rehanedly

2022-04-06 23:10 UTC, hassantanveer97 requested changes
Please run this through Grammarly once as well

2022-04-06 23:10 UTC, hassantanveer97 commented on docs/decisions/0001-show-input-file-read-code.rst
> + - We need a solution where we can add option in ora setting that ask author if the system should display input fileread code by default in the editor orr not
```suggestion
 - We need a solution where we can add option in ORA settings that asks the author if the system should display input file-read code by default in the editor or not
```

2022-04-08 13:24 UTC, hassantanveer97 approved these changes

2022-04-12 08:49 UTC, HussainTaj-arbisoft approved these changes
Looks good. Please run it through a grammar checker (like Grammarly) once.

2022-04-12 22:12 UTC, merged