Lt 534
arbisoft/edx-ora2-1 pull request #60
Opened 2022-04-13 09:27 UTC by rehanedly

2022-04-18 11:26 UTC, HussainTaj-arbisoft requested changes
1. Shouldn't the base of this PR be `litmustest.develop` instead of `litmustest.staging`?
2. This PR includes migrations of fields we did not change. I think we should not do this on our side because the original (newer) codebase would have the new fields. If we need the migrations we should update the repos/packages.
3. We need to run the following commands to generate a minified buddle of the JS, otherwise this won't work on the server.

```bash
make lms-shell
cd /edx/src/edx-ora2-1/
make javascript
```

2022-04-18 11:26 UTC, HussainTaj-arbisoft commented on openassessment/assessment/migrations/0004_auto_20220411_2015.py
> +        ),
I think we should remove this.

2022-04-18 11:26 UTC, HussainTaj-arbisoft commented on openassessment/workflow/migrations/0003_auto_20220411_2015.py
> +        migrations.AlterField(
I think we should remove this.

2022-04-18 11:26 UTC, HussainTaj-arbisoft commented on openassessment/workflow/migrations/0004_auto_20220411_2017.py
> +        migrations.AlterField(
I think we should remove this.

2022-04-18 22:33 UTC, rehanedly commented
> 1. Shouldn't the base of this PR be `litmustest.develop` instead of `litmustest.staging`?
> 2. This PR includes migrations of fields we did not change. I think we should not do this on our side because the original (newer) codebase would have the new fields. If we need the migrations we should update the repos/packages.
> 3. We need to run the following commands to generate a minified buddle of the JS, otherwise this won't work on the server.
> 
> ```shell
> make lms-shell
> cd /edx/src/edx-ora2-1/
> make javascript
> ```

Fixed these issues

2022-04-19 09:26 UTC, HussainTaj-arbisoft approved these changes
LGTM 👍

2022-04-20 08:03 UTC, merged