[LT-707] Read test cases from db
arbisoft/edx-ora2-1 pull request #78
Opened 2022-10-19 13:43 UTC by hassantanveer97

- If AssessmentQuestionXblock mapping has been established, test cases are read from DB
- Otherwise it falls back to reading test cases from the files
- Tested:
  - Server shell
  - Epic box
  - Code read from files
  - Code read from stdin

2022-10-20 08:14 UTC, HussainTaj-arbisoft requested changes

2022-10-20 08:14 UTC, HussainTaj-arbisoft commented on openassessment/xblock/job_sample_grader/code_grader.py
> +                test_cases = question.metadata[run_type]
```suggestion
            try:
                test_cases = json.loads(question.metadata).get(run_type, {})
            except:
                test_cases = question.metadata.get(run_type, {})
```

2022-10-20 08:14 UTC, HussainTaj-arbisoft commented on openassessment/xblock/job_sample_grader/code_grader.py
> +            for case_number in test_cases:
```suggestion
            for case_number in sorted(test_cases.keys()):
```

2022-10-20 08:14 UTC, HussainTaj-arbisoft commented on openassessment/xblock/job_sample_grader/code_grader.py
> +
Won't this delete the grader data in the case when a block mapping does not exist?

2022-10-20 08:14 UTC, HussainTaj-arbisoft commented on openassessment/xblock/job_sample_grader/code_grader.py
> +        else:
Let's refactor this code. This function is huge.

Can we do something like self.get_test_case_files() ?

2022-10-31 08:59 UTC, HussainTaj-arbisoft reviewed
There's an empty `openassessment/xblock/job_sample_grader/tmp_data/empty.in` file committed.

2022-10-31 11:10 UTC, hassantanveer97 commented
> There's an empty `openassessment/xblock/job_sample_grader/tmp_data/empty.in` file committed.

@HussainTaj-arbisoft Its deletion of that empty file, not addition

2022-10-31 11:39 UTC, HussainTaj-arbisoft approved these changes

2022-10-31 11:42 UTC, merged